---
dev_name: bosh-vcloud-cpi-release-24-custom
latest_release_filename: /var/release-io/suman/bosh-vcloud-cpi-release-24-custom/dev_releases/bosh-vcloud-cpi-release-24-custom/bosh-vcloud-cpi-release-24-custom-0+dev.2.yml
